version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: BCSS
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ../api
    ports:
    - "8000:8000"
    depends_on:
    - db

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      # Mapea carpeta de configuración (dashboards y datasources)
      - ./grafana/provisioning:/etc/grafana/provisioning
      # Mapea carpeta dashboards guardas en archivos JSON
      - ./grafana/dashboards:/var/lib/grafana/dashboards
volumes:
  postgres_data:
  grafana_data: